# Generated by Django 5.0.4 on 2024-04-22 11:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="product",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
