# Generated by Django 5.0.4 on 2024-06-28 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_remove_comment_parent_id_reply"),
    ]

    operations = [
        migrations.AddField(
            model_name="reply",
            name="blog",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.blog",
            ),
        ),
    ]
