# Generated by Django 5.0.4 on 2024-06-28 15:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_reply_blog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reply",
            name="blog",
        ),
    ]
