# Generated by Django 5.0.4 on 2024-06-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0007_remove_reply_blog"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="pembelian",
            field=models.CharField(blank=True, null=True),
        ),
    ]
