# Generated by Django 5.0.4 on 2024-06-29 10:16

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0008_product_pembelian"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True,
                editable=False,
                populate_from="product_name",
                unique=True,
            ),
        ),
    ]
